### ISSUE TITLE
Trying to get the country while pulling movie.details()

### ISSUE THREAD

**Issue by eag5834** [AnthonyBloomer/tmdbv3api#82] opened 2021-04-13 20:53 UTC
I know that production_countries is an array with the country name and abbreviation included. But I'm having trouble trying to pull them with rest of the detail data that I want.  The goal is to create a data set of movies that went to theaters in North America.  I have attempted adding 'region' in my discovery pool which I do before this but it didn't seem to work.

Here is my code so far for that portion (movie_info is a list of movie id's for movies that were released january 2019):

`US_movie_info = []

for k in movie_info:
    result2 = movie.details(str(k))
    US_movie_info.append([result2.id, result2.title, result2.overview, result2.release_date, 
                         result2.budget, result2.runtime])
df_us_movie_info = pd.DataFrame(US_movie_info)`

**Comment by BackrndSource** [comment] 2021-04-15 00:30
I don't understand where the problem is. What I see is that the code does not store `production_countries` in the array.  Add `result2.production_countries.name` in to the append function params and voila, right?

Look at oficial tmdbv3api docs for get more information. Or in `examples` folder of the projet, `test` folder or `tmdbv3api/objs` folder.

**Comment by BackrndSource** [comment] 2021-04-18 22:01
I will close this is issue beacause is not related with tmdbv3api code.

**Closed by BackrndSource** 2021-04-18 22:01 UTC
